In [1]:
import sys
import time
import numpy as np
import pickle
import importlib

In [2]:
from qiskit import Aer, IBMQ
from qiskit.ignis.mitigation.measurement import TensoredMeasFitter
from libs_qrem import LeastNormFilter

/var/folders/vr/d82vcp297v78vk4sb0_nzzdc0000gn/T/ipykernel_6982/1392086703.py:2: DeprecationWarning: The qiskit.ignis package is deprecated and has been supersceded by the qiskit-experiments project. Refer to the migration guide: https://github.com/Qiskit/qiskit-ignis#migration-guide on how to migrate to the new project.
  from qiskit.ignis.mitigation.measurement import TensoredMeasFitter


In [3]:
with open("pkls/raw_hist_list.pkl", "rb") as f:
    raw_hist_list = pickle.load(f)
with open("pkls/results_meas_cal.pkl", "rb") as f:
    results_meas_cal = pickle.load(f)

In [4]:
n = 92
mit_pattern = [[i] for i in range(n)]
meas_fitter = TensoredMeasFitter(results_meas_cal[0], mit_pattern=mit_pattern)
xz_lnp_mitigator_list = []
xz_lnp_mitigator_list.append( LeastNormFilter(n, meas_fitter.cal_matrices) )

In [5]:
n = 92
mit_pattern = [[i] for i in range(n)]
meas_fitter = TensoredMeasFitter(results_meas_cal[0], mit_pattern=mit_pattern)
zx_lnp_mitigator_list = []
zx_lnp_mitigator_list.append( LeastNormFilter(n, meas_fitter.cal_matrices) ) 

In [8]:
meas_fitter.cal_matrices

[array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0.,

In [6]:
lnp_hist_list = []
xz_lnp_total_times = []
zx_lnp_total_times = []
print(n, "qubits")

t1 = time.perf_counter()
lnp_hist_list.append( xz_lnp_mitigator_list[0].apply(raw_hist_list[0]) )
t2 = time.perf_counter()
xz_lnp_total_times.append(t2 - t1)
print("xz", t2 - t1, "s")

t3 = time.perf_counter()
lnp_hist_list.append( zx_lnp_mitigator_list[0].apply(raw_hist_list[1]) )
t4 = time.perf_counter()
zx_lnp_total_times.append(t4 - t3)
print("zx", t4 - t3, "s")

92 qubits


NameError: name 'xz_lnp_mitigator' is not defined

In [ ]:
raw_hist_list

In [ ]:
with open("./pkls/lnp_hist_list.pkl", "wb") as f:
    pickle.dump(lnp_hist_list, f)

In [ ]:
with open("./pkls/lnp_total_times.pkl", "wb") as f:
    pickle.dump({"xz": xz_lnp_total_times, "zx": zx_lnp_total_times}, f)

In [ ]:
xz_lnp_times = []
zx_lnp_times = []
xz_lnp_times.append( xz_lnp_mitigator_list[0].times() )
zx_lnp_times.append( zx_lnp_mitigator_list[0].times() )

In [ ]:
with open("./pkls/lnp_times.pkl", "wb") as f:
    pickle.dump({"xz": xz_lnp_times, "zx": zx_lnp_times}, f)

In [ ]:
xz_lnp_mitigators = []
for i in range(max_length):
    xz_lnp_mitigators.append({"indices_to_keys_vector":xz_lnp_mitigator_list[i].indices_to_keys_vector(),
                              # "mitigated_hist":xz_lnp_mitigator_list[i].mitigated_hist(),
                              "one_norm":xz_lnp_mitigator_list[i].one_norm(),
                              # "reduced_inv_A":xz_lnp_mitigator_list[i].reduced_inv_A(),
                              "sum_of_x":xz_lnp_mitigator_list[i].sum_of_x(),
                              "sum_of_x_hat":xz_lnp_mitigator_list[i].sum_of_x_hat(),
                              "sum_of_x_tilde":xz_lnp_mitigator_list[i].sum_of_x_tilde(),
                              # "times":xz_lnp_mitigator_list[i].times(),
                              "x_s":xz_lnp_mitigator_list[i].x_s(),
                              "x_hat":xz_lnp_mitigator_list[i].x_hat(),
                              "x_tilde":xz_lnp_mitigator_list[i].x_tilde(),
                              })
    print(i, "finished")

In [ ]:
zx_lnp_mitigators = []
for i in range(max_length):
    zx_lnp_mitigators.append({"indices_to_keys_vector":zx_lnp_mitigator_list[i].indices_to_keys_vector(),
                              # "mitigated_hist":zx_lnp_mitigator_list[i].mitigated_hist(),
                              "one_norm":zx_lnp_mitigator_list[i].one_norm(),
                              # "reduced_inv_A":zx_lnp_mitigator_list[i].reduced_inv_A(),
                              "sum_of_x":zx_lnp_mitigator_list[i].sum_of_x(),
                              "sum_of_x_hat":zx_lnp_mitigator_list[i].sum_of_x_hat(),
                              "sum_of_x_tilde":zx_lnp_mitigator_list[i].sum_of_x_tilde(),
                              # "times":zx_lnp_mitigator_list[i].times(),
                              "x_s":zx_lnp_mitigator_list[i].x_s(),
                              "x_hat":zx_lnp_mitigator_list[i].x_hat(),
                              "x_tilde":zx_lnp_mitigator_list[i].x_tilde(),
                              })
    print(i, "finished")

In [ ]:
with open("./pkls/lnp_mitigator_list.pkl", "wb") as f:
    pickle.dump({"xz": xz_lnp_mitigators, "zx": zx_lnp_mitigators}, f)